/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode= new crud();
        mycode.tampilDataBarang(tabelDataBarang, "SELECT*FROM data_barang");
        mycode.tampilDataKategori(tabelKategori, "SELECT*FROM kategori");
        mycode.tampilDataIDServer(tabelIDServer, "SELECT*FROM id_server");
        mycode.tampilDataServer(tabelDataServer, "SELECT*FROM data_server");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlkategori = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtKategori = new javax.swing.JTextField();
        btnHpsKategori = new javax.swing.JButton();
        btnSmpnKategori = new javax.swing.JButton();
        btnUbhKategori = new javax.swing.JButton();
        txtCariKategori = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelKategori = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtIndexKategori = new javax.swing.JTextField();
        pnlDataBarang = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtKategoriBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        txtHargaPetani = new javax.swing.JTextField();
        btnHpsDataBarang = new javax.swing.JButton();
        btnSmpnDataBarang = new javax.swing.JButton();
        btnUbhDataBarang = new javax.swing.JButton();
        txtCariDataBarang = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelDataBarang = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        txtHargaPengepul = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtHargaGrosir = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtHargaKonsumen = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        pnlDataServer = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        txtNamaServer = new javax.swing.JTextField();
        txtAlamatServer = new javax.swing.JTextField();
        btnHpsDataServer = new javax.swing.JButton();
        btnSmpnDataServer = new javax.swing.JButton();
        btnUbhDataServer = new javax.swing.JButton();
        txtCariDataServer = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabelDataServer = new javax.swing.JTable();
        jLabel46 = new javax.swing.JLabel();
        txtIndexServer = new javax.swing.JTextField();
        pnlIdServer = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        txtAlamatId = new javax.swing.JTextField();
        btnHpsIDServer = new javax.swing.JButton();
        btnSmpnIDServer = new javax.swing.JButton();
        btnUbhIDServer = new javax.swing.JButton();
        txtCariIDServer = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelIDServer = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        txtNamaId = new javax.swing.JTextField();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnKategori = new javax.swing.JButton();
        btnDataBarang = new javax.swing.JButton();
        btnDataServer = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnIdServer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlkategori.setBackground(new java.awt.Color(204, 204, 204));
        pnlkategori.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Kategori");
        pnlkategori.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtKategori.setBackground(new java.awt.Color(255, 255, 255));
        txtKategori.setForeground(new java.awt.Color(0, 0, 0));
        txtKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKategoriActionPerformed(evt);
            }
        });
        pnlkategori.add(txtKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        btnHpsKategori.setText("HAPUS");
        btnHpsKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsKategoriActionPerformed(evt);
            }
        });
        pnlkategori.add(btnHpsKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnKategori.setText("SIMPAN");
        btnSmpnKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnKategoriActionPerformed(evt);
            }
        });
        pnlkategori.add(btnSmpnKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhKategori.setText("UBAH");
        btnUbhKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhKategoriActionPerformed(evt);
            }
        });
        pnlkategori.add(btnUbhKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariKategori.setBackground(new java.awt.Color(255, 255, 255));
        txtCariKategori.setForeground(new java.awt.Color(0, 0, 0));
        txtCariKategori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKategoriKeyReleased(evt);
            }
        });
        pnlkategori.add(txtCariKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 370, -1));

        tabelKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelKategori);

        pnlkategori.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 480, 155));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("ID Kategori");
        pnlkategori.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIndexKategori.setBackground(new java.awt.Color(255, 255, 255));
        txtIndexKategori.setForeground(new java.awt.Color(0, 0, 0));
        txtIndexKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIndexKategoriActionPerformed(evt);
            }
        });
        pnlkategori.add(txtIndexKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        Content.add(pnlkategori, "card4");

        pnlDataBarang.setBackground(new java.awt.Color(204, 204, 204));
        pnlDataBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Harga Petani");
        pnlDataBarang.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Kategori");
        pnlDataBarang.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Nama Barang");
        pnlDataBarang.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtKategoriBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtKategoriBarang.setForeground(new java.awt.Color(0, 0, 0));
        pnlDataBarang.add(txtKategoriBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtNamaBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaBarang.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarangActionPerformed(evt);
            }
        });
        pnlDataBarang.add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtHargaPetani.setBackground(new java.awt.Color(255, 255, 255));
        txtHargaPetani.setForeground(new java.awt.Color(0, 0, 0));
        pnlDataBarang.add(txtHargaPetani, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsDataBarang.setText("HAPUS");
        btnHpsDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsDataBarangActionPerformed(evt);
            }
        });
        pnlDataBarang.add(btnHpsDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 90, -1));

        btnSmpnDataBarang.setText("SIMPAN");
        btnSmpnDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnDataBarangActionPerformed(evt);
            }
        });
        pnlDataBarang.add(btnSmpnDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 90, -1));

        btnUbhDataBarang.setText("UBAH");
        btnUbhDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhDataBarangActionPerformed(evt);
            }
        });
        pnlDataBarang.add(btnUbhDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 90, -1));

        txtCariDataBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtCariDataBarang.setForeground(new java.awt.Color(0, 0, 0));
        txtCariDataBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariDataBarangKeyReleased(evt);
            }
        });
        pnlDataBarang.add(txtCariDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 370, -1));

        tabelDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabelDataBarang);

        pnlDataBarang.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 490, 155));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Kode Barang");
        pnlDataBarang.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtKodeBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtKodeBarang.setForeground(new java.awt.Color(0, 0, 0));
        txtKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeBarangActionPerformed(evt);
            }
        });
        pnlDataBarang.add(txtKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        txtHargaPengepul.setBackground(new java.awt.Color(255, 255, 255));
        txtHargaPengepul.setForeground(new java.awt.Color(0, 0, 0));
        pnlDataBarang.add(txtHargaPengepul, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Harga Pengepul");
        pnlDataBarang.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 130, -1));

        txtHargaGrosir.setBackground(new java.awt.Color(255, 255, 255));
        txtHargaGrosir.setForeground(new java.awt.Color(0, 0, 0));
        pnlDataBarang.add(txtHargaGrosir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        jLabel42.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Harga Grosir");
        pnlDataBarang.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));

        txtHargaKonsumen.setBackground(new java.awt.Color(255, 255, 255));
        txtHargaKonsumen.setForeground(new java.awt.Color(0, 0, 0));
        pnlDataBarang.add(txtHargaKonsumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 220, -1));

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Harga Konsumen");
        pnlDataBarang.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 150, -1));

        Content.add(pnlDataBarang, "card3");

        pnlDataServer.setBackground(new java.awt.Color(204, 204, 204));
        pnlDataServer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Alamat Server");
        pnlDataServer.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 130, -1));

        jLabel44.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("IP");
        pnlDataServer.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel45.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Nama Server");
        pnlDataServer.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtIP.setBackground(new java.awt.Color(255, 255, 255));
        txtIP.setForeground(new java.awt.Color(0, 0, 0));
        pnlDataServer.add(txtIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtNamaServer.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaServer.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaServerActionPerformed(evt);
            }
        });
        pnlDataServer.add(txtNamaServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtAlamatServer.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatServer.setForeground(new java.awt.Color(0, 0, 0));
        pnlDataServer.add(txtAlamatServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsDataServer.setText("HAPUS");
        btnHpsDataServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsDataServerActionPerformed(evt);
            }
        });
        pnlDataServer.add(btnHpsDataServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnDataServer.setText("SIMPAN");
        btnSmpnDataServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnDataServerActionPerformed(evt);
            }
        });
        pnlDataServer.add(btnSmpnDataServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhDataServer.setText("UBAH");
        btnUbhDataServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhDataServerActionPerformed(evt);
            }
        });
        pnlDataServer.add(btnUbhDataServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariDataServer.setBackground(new java.awt.Color(255, 255, 255));
        txtCariDataServer.setForeground(new java.awt.Color(0, 0, 0));
        txtCariDataServer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariDataServerKeyReleased(evt);
            }
        });
        pnlDataServer.add(txtCariDataServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 370, -1));

        tabelDataServer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tabelDataServer);

        pnlDataServer.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 480, 155));

        jLabel46.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("ID Server");
        pnlDataServer.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIndexServer.setBackground(new java.awt.Color(255, 255, 255));
        txtIndexServer.setForeground(new java.awt.Color(0, 0, 0));
        txtIndexServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIndexServerActionPerformed(evt);
            }
        });
        pnlDataServer.add(txtIndexServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        Content.add(pnlDataServer, "card5");

        pnlIdServer.setBackground(new java.awt.Color(204, 204, 204));
        pnlIdServer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Alamat ID");
        pnlIdServer.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtAlamatId.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatId.setForeground(new java.awt.Color(0, 0, 0));
        txtAlamatId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatIdActionPerformed(evt);
            }
        });
        pnlIdServer.add(txtAlamatId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        btnHpsIDServer.setText("HAPUS");
        btnHpsIDServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsIDServerActionPerformed(evt);
            }
        });
        pnlIdServer.add(btnHpsIDServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnIDServer.setText("SIMPAN");
        btnSmpnIDServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnIDServerActionPerformed(evt);
            }
        });
        pnlIdServer.add(btnSmpnIDServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhIDServer.setText("UBAH");
        btnUbhIDServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhIDServerActionPerformed(evt);
            }
        });
        pnlIdServer.add(btnUbhIDServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariIDServer.setBackground(new java.awt.Color(255, 255, 255));
        txtCariIDServer.setForeground(new java.awt.Color(0, 0, 0));
        txtCariIDServer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariIDServerKeyReleased(evt);
            }
        });
        pnlIdServer.add(txtCariIDServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 370, -1));

        tabelIDServer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tabelIDServer);

        pnlIdServer.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 480, 155));

        jLabel37.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Nama ID");
        pnlIdServer.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtNamaId.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaId.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaIdActionPerformed(evt);
            }
        });
        pnlIdServer.add(txtNamaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        Content.add(pnlIdServer, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aplikasi Manajemen Data Komoditas & Infrastruktur Pertanian");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(153, 153, 153));
        Menu.setForeground(new java.awt.Color(255, 255, 255));

        btnKategori.setBackground(new java.awt.Color(255, 255, 255));
        btnKategori.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKategori.setForeground(new java.awt.Color(0, 0, 0));
        btnKategori.setText("KATEGORI");
        btnKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategoriActionPerformed(evt);
            }
        });

        btnDataBarang.setBackground(new java.awt.Color(255, 255, 255));
        btnDataBarang.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDataBarang.setForeground(new java.awt.Color(0, 0, 0));
        btnDataBarang.setText("DATA BARANG");
        btnDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataBarangActionPerformed(evt);
            }
        });

        btnDataServer.setBackground(new java.awt.Color(255, 255, 255));
        btnDataServer.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDataServer.setForeground(new java.awt.Color(0, 0, 0));
        btnDataServer.setText("DATA SERVER");
        btnDataServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataServerActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnIdServer.setBackground(new java.awt.Color(255, 255, 255));
        btnIdServer.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnIdServer.setForeground(new java.awt.Color(0, 0, 0));
        btnIdServer.setText("ID SERVER");
        btnIdServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDataBarang)
                    .addComponent(btnKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDataServer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIdServer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, 0))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDataBarang, btnDataServer, btnIdServer, btnKategori});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDataBarang)
                .addGap(18, 18, 18)
                .addComponent(btnDataServer)
                .addGap(18, 18, 18)
                .addComponent(btnIdServer)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDataBarang, btnDataServer, btnIdServer, btnKategori});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategoriActionPerformed
        Content.removeAll(); 
        Content.add(pnlkategori);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnKategoriActionPerformed

    private void btnDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataBarangActionPerformed
        Content.removeAll(); 
        Content.add(pnlDataBarang);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnDataBarangActionPerformed

    private void btnDataServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataServerActionPerformed
        Content.removeAll(); 
        Content.add(pnlDataServer);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnDataServerActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnIdServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdServerActionPerformed
        Content.removeAll(); 
        Content.add(pnlIdServer);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnIdServerActionPerformed

    private void txtCariKategoriKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKategoriKeyReleased
        String c = txtCariKategori.getText();
        // Pola 01 (Tidak Aman) sesuai contoh Anda
        String cari = "SELECT*FROM Kategori WHERE Index_Kategori LIKE '%"+c+"%'"+
                      "OR Kategori LIKE '%"+c+"%'";
        mycode.tampilDataKategori(tabelKategori, cari);
    }//GEN-LAST:event_txtCariKategoriKeyReleased

    private void btnUbhKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhKategoriActionPerformed
        try {
            mycode.ubahKategori(txtIndexKategori.getText(), txtKategori.getText());

            mycode.tampilDataKategori(tabelKategori, "SELECT*FROM Kategori");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhKategoriActionPerformed

    private void btnSmpnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnKategoriActionPerformed
        try {
            if(txtIndexKategori.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Index Kategori Belum Diisi");
                txtIndexKategori.requestFocus();
            } else if(txtKategori.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Kategori Belum Diisi");
                txtKategori.requestFocus();
            } else {
                mycode.simpanKategori02(txtIndexKategori.getText(), txtKategori.getText());

                mycode.tampilDataKategori(tabelKategori, "SELECT*FROM Kategori");

                if (mycode.duplikasi == true){
                    txtKategori.setText(mycode.CEK_KATEGORI_KAT);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnKategoriActionPerformed

    private void btnHpsKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsKategoriActionPerformed
        try {
            mycode.hapusKategori(txtIndexKategori.getText());
            mycode.tampilDataKategori(tabelKategori, "SELECT*FROM Kategori");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsKategoriActionPerformed

    private void txtKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKategoriActionPerformed

    private void txtIndexKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIndexKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIndexKategoriActionPerformed

    private void txtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBarangActionPerformed

    private void btnHpsDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsDataBarangActionPerformed
        try {
            mycode.hapusDataBarang(txtKodeBarang.getText());
            mycode.tampilDataBarang(tabelDataBarang, "SELECT*FROM Data_Barang");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsDataBarangActionPerformed

    private void btnSmpnDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnDataBarangActionPerformed
        try {
            if(txtKodeBarang.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Kode Barang Belum Diisi");
                txtKodeBarang.requestFocus();
            } else if(txtNamaBarang.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Barang Belum Diisi");
                txtNamaBarang.requestFocus();
            } else if(txtKategoriBarang.getText().isEmpty()){ 
                JOptionPane.showMessageDialog(null, "Kategori Belum Diisi");
                txtKategoriBarang.requestFocus();
            } else if(txtHargaPetani.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Harga Petani Belum Diisi");
                txtHargaPetani.requestFocus();
            } else if(txtHargaPengepul.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Harga Pengepul Belum Diisi");
                txtHargaPengepul.requestFocus();
            } else if(txtHargaGrosir.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Harga Grosir Belum Diisi");
                txtHargaGrosir.requestFocus();
            } else if(txtHargaKonsumen.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Harga Konsumen Belum Diisi");
                txtHargaKonsumen.requestFocus();
            } else {
                mycode.simpanDataBarang02(txtKodeBarang.getText(), txtNamaBarang.getText(),
                                          txtKategoriBarang.getText(), txtHargaPetani.getText(),
                                          txtHargaPengepul.getText(), txtHargaGrosir.getText(),
                                          txtHargaKonsumen.getText());

                mycode.tampilDataBarang(tabelDataBarang, "SELECT*FROM Data_Barang");

                if (mycode.duplikasi == true){
                    txtNamaBarang.setText(mycode.CEK_NAMA_BARANG);
                    txtKategoriBarang.setText(mycode.CEK_KATEGORI_BRG);
                    txtHargaPetani.setText(mycode.CEK_HARGA_PETANI);
                    txtHargaPengepul.setText(mycode.CEK_HARGA_PENGEPUL);
                    txtHargaGrosir.setText(mycode.CEK_HARGA_GROSIR);
                    txtHargaKonsumen.setText(mycode.CEK_HARGA_KONSUMEN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnDataBarangActionPerformed

    private void btnUbhDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhDataBarangActionPerformed
        try {
            mycode.ubahDataBarang(txtKodeBarang.getText(), txtNamaBarang.getText(),
                                  txtKategoriBarang.getText(), txtHargaPetani.getText(),
                                  txtHargaPengepul.getText(), txtHargaGrosir.getText(),
                                  txtHargaKonsumen.getText());

            mycode.tampilDataBarang(tabelDataBarang, "SELECT*FROM Data_Barang");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhDataBarangActionPerformed

    private void txtCariDataBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariDataBarangKeyReleased
        String c = txtCariDataBarang.getText();
        String cari = "SELECT*FROM Data_Barang WHERE Kode_Barang LIKE '%"+c+"%'"+
                      "OR Nama_barang LIKE '%"+c+"%' OR Kategori LIKE '%"+c+"%'"+
                      "OR Harga_petani LIKE '%"+c+"%' OR Harga_konsumen LIKE '%"+c+"%'";
        mycode.tampilDataBarang(tabelDataBarang, cari);
    }//GEN-LAST:event_txtCariDataBarangKeyReleased

    private void txtKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeBarangActionPerformed

    private void txtAlamatIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatIdActionPerformed

    private void btnHpsIDServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsIDServerActionPerformed
        try {
            mycode.hapusIDServer(txtNamaId.getText());
            mycode.tampilDataIDServer(tabelIDServer, "SELECT*FROM ID_Server");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsIDServerActionPerformed

    private void btnSmpnIDServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnIDServerActionPerformed
        try {
            if(txtNamaId.getText().isEmpty()){ // Asumsi nama: txtNamaId
                JOptionPane.showMessageDialog(null, "Nama Belum Diisi");
                txtNamaId.requestFocus();
            } else if(txtAlamatId.getText().isEmpty()){ // Asumsi nama: txtAlamatId
                JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
                txtAlamatId.requestFocus();
            } else {
                mycode.simpanIDServer02(txtNamaId.getText(), txtAlamatId.getText());

                // Refresh tabel
                mycode.tampilDataIDServer(tabelIDServer, "SELECT*FROM ID_Server");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtAlamatId.setText(mycode.CEK_ALAMAT_ID);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnIDServerActionPerformed

    private void btnUbhIDServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhIDServerActionPerformed
        try {
            mycode.ubahIDServer(txtNamaId.getText(), txtAlamatId.getText());

            // Refresh tabel
            mycode.tampilDataIDServer(tabelIDServer, "SELECT*FROM ID_Server");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhIDServerActionPerformed

    private void txtCariIDServerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariIDServerKeyReleased
        String c = txtCariIDServer.getText();
        String cari = "SELECT*FROM ID_Server WHERE Nama LIKE '%"+c+"%'"+
                      "OR Alamat LIKE '%"+c+"%'";
        mycode.tampilDataIDServer(tabelIDServer, cari);                                  
    }//GEN-LAST:event_txtCariIDServerKeyReleased

    private void txtNamaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaIdActionPerformed

    private void txtNamaServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaServerActionPerformed

    private void btnHpsDataServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsDataServerActionPerformed
        try {
            mycode.hapusDataServer(txtIndexServer.getText());
            mycode.tampilDataServer(tabelDataServer, "SELECT*FROM Data_server");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsDataServerActionPerformed

    private void btnSmpnDataServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnDataServerActionPerformed
        try {
            if(txtIndexServer.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Index Server Belum Diisi");
                txtIndexServer.requestFocus();
            } else if(txtNamaServer.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Server Belum Diisi");
                txtNamaServer.requestFocus();
            } else if(txtIP.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "IP Belum Diisi");
                txtIP.requestFocus();
            } else if(txtAlamatServer.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "Alamat Belum Diisi");
                txtAlamatServer.requestFocus();
            } else {
                mycode.simpanDataServer02(txtIndexServer.getText(), txtNamaServer.getText(),
                                          txtIP.getText(), txtAlamatServer.getText());

                // Refresh tabel
                mycode.tampilDataServer(tabelDataServer, "SELECT*FROM Data_server");

                // Cek duplikasi
                if (mycode.duplikasi == true){
                    txtNamaServer.setText(mycode.CEK_NAMASERVER);
                    txtIP.setText(mycode.CEK_IP);
                    txtAlamatServer.setText(mycode.CEK_ALAMAT_SERVER);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnDataServerActionPerformed

    private void btnUbhDataServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhDataServerActionPerformed
        try {
            mycode.ubahDataServer(txtIndexServer.getText(), txtNamaServer.getText(),
                                  txtIP.getText(), txtAlamatServer.getText());

            mycode.tampilDataServer(tabelDataServer, "SELECT*FROM Data_server");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhDataServerActionPerformed

    private void txtCariDataServerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariDataServerKeyReleased
        String c = txtCariDataServer.getText();
        String cari = "SELECT*FROM Data_server WHERE Index_Server LIKE '%"+c+"%'"+
                      "OR NamaServer LIKE '%"+c+"%' OR IP LIKE '%"+c+"%'"+
                      "OR Alamat LIKE '%"+c+"%'";
        mycode.tampilDataServer(tabelDataServer, cari);
    }//GEN-LAST:event_txtCariDataServerKeyReleased

    private void txtIndexServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIndexServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIndexServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnDataBarang;
    private javax.swing.JButton btnDataServer;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsDataBarang;
    private javax.swing.JButton btnHpsDataServer;
    private javax.swing.JButton btnHpsIDServer;
    private javax.swing.JButton btnHpsKategori;
    private javax.swing.JButton btnIdServer;
    private javax.swing.JButton btnKategori;
    private javax.swing.JButton btnSmpnDataBarang;
    private javax.swing.JButton btnSmpnDataServer;
    private javax.swing.JButton btnSmpnIDServer;
    private javax.swing.JButton btnSmpnKategori;
    private javax.swing.JButton btnUbhDataBarang;
    private javax.swing.JButton btnUbhDataServer;
    private javax.swing.JButton btnUbhIDServer;
    private javax.swing.JButton btnUbhKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel pnlDataBarang;
    private javax.swing.JPanel pnlDataServer;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlIdServer;
    private javax.swing.JPanel pnlkategori;
    private javax.swing.JTable tabelDataBarang;
    private javax.swing.JTable tabelDataServer;
    private javax.swing.JTable tabelIDServer;
    private javax.swing.JTable tabelKategori;
    private javax.swing.JTextField txtAlamatId;
    private javax.swing.JTextField txtAlamatServer;
    private javax.swing.JTextField txtCariDataBarang;
    private javax.swing.JTextField txtCariDataServer;
    private javax.swing.JTextField txtCariIDServer;
    private javax.swing.JTextField txtCariKategori;
    private javax.swing.JTextField txtHargaGrosir;
    private javax.swing.JTextField txtHargaKonsumen;
    private javax.swing.JTextField txtHargaPengepul;
    private javax.swing.JTextField txtHargaPetani;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtIndexKategori;
    private javax.swing.JTextField txtIndexServer;
    private javax.swing.JTextField txtKategori;
    private javax.swing.JTextField txtKategoriBarang;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNamaId;
    private javax.swing.JTextField txtNamaServer;
    // End of variables declaration//GEN-END:variables
}
